### PR TITLE
[feat] generate rpm packaging

### PR DESCRIPTION
**Pull request by 4383**
Adding rpm packaging #5

### CODE REVIEW

**Comment by 4383** [comment]
based on [rpm fedora python packaging best practices](https://fedoraproject.org/wiki/Packaging:Python)

**Comment by AntoineCezar** [comment]
Thanks for this nice PR.

Question: I have no knowledge in packaging. does this rpm specific to fedora ?

Request: The feature should be an option with post_gen_project hook to remove unwanted files.

**Comment by 4383** [comment]
You are welcome ;)

Response: Yes it's based on fedora best practices but can be compatible with others rhel like distributions. Just package naming convention can change between distribution but actions are the sames.

Request response: we can manage sub package type with post_gen_project hook in the next days I try to share this with this PR

**Comment by AntoineCezar** [comment]
I've landed the base docs template so you can add packaging related content. I'll merge once the docs are ok. Well see later hooks and fedora/rhel details.
Thanks for your work. Packaging is really not my field.

**Comment by AntoineCezar** [comment]
See #16 for followups

**Pull request merged**
