### PR TITLE
[feat] generate apk for alpine linux

### PR DESCRIPTION
**Pull request by 4383**
APKBUILD for alpine linux

### CODE REVIEW

**Comment by 4383** [comment]
implement #7

**Comment by AntoineCezar** [comment]
Has for the RPM one, thanks for this PR.

Alpine Linux looks like a rather confidential distribution to support. I'm not sure it's a good idea to add it for now. Do you?

**Comment by 4383** [comment]
It's a little bit to maintain no more actions are needed...
We can manage this kind of package with post hook and let's users choose if it's needed or not.
IMHO this feature it's just goodies with no more maintains after generate step (for our). User choose to use or not to use with the work needed behind the hood.

**Comment by AntoineCezar** [comment]
Since you contribute and seems to care about this distribution, let's have it. I'll merge once the docs templates are ok.

**Pull request closed without merging**
